packages:
  - packages/*
  - apps/*

allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@swc/core': true
  cbor-extract: false
  esbuild: true

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - argon2

minimumReleaseAgeExclude:
  - '@nemnesia/symbol-websocket@0.2.2 || 1.0.0'

onlyBuiltDependencies:
  - esbuild
